refactor(oxfmt): Use `Box<FormatOptions>` for `ResolvedOptions` (#17772)
Preparation for #17576

```
error: large size difference between variants
  --> apps/oxfmt/src/core/config.rs:51:1
   |
51 | /   pub enum ResolvedOptions {
52 | |       /// For JS/TS files formatted by oxc_formatter.
53 | | /     OxcFormatter {
54 | | |         format_options: FormatOptions,
55 | | |         /// For embedded language formatting (e.g., CSS in template literals)
56 | | |         external_options: Value,
57 | | |         insert_final_newline: bool,
58 | | |     },
   | | |_____- the largest variant contains at least 281 bytes
...  |
66 | | /     ExternalFormatterPackageJson {
67 | | |         external_options: Value,
68 | | |         sort_package_json: Option<sort_package_json::SortOptions>,
69 | | |         insert_final_newline: bool,
70 | | |     },
   | | |_____- the second-largest variant contains at least 75 bytes
71 | |   }
   | |___^ the entire enum is at least 288 bytes
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#large_enum_variant
   = note: `-D clippy::large-enum-variant` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::large_enum_variant)]`
help: consider boxing the large fields or introducing indirection in some other way to reduce the total size of the enum
   |
54 -         format_options: FormatOptions,
54 +         format_options: Box<FormatOptions>,
   |

```