fix(oxfmt): ignore symlink ends with `.js` (#15270)
### Problem

if we have a directory like this and run oxfmt in it

```bash
.
├── bar.js -> foo
├── foo
│   └── file.js
└── root.js
```

It will panic like this: 

```bash
thread '<unnamed>' panicked at apps/oxfmt/src/service.rs:51:52:
Failed to read file: Os { code: 21, kind: IsADirectory, message: "Is a directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

because it try reading `bar.js` as a `.js` file but it is actually a
symlink

As I know, symlink is common in some projects with complex script or in
pnpm node_modules

### Fixes

Fixed by using `FileType::is_file` instead of `!FileType::is_dir`

Thanks ❤️

---------

Signed-off-by: Yuji Sugiura <6259812+leaysgur@users.noreply.github.com>
Co-authored-by: Yuji Sugiura <6259812+leaysgur@users.noreply.github.com>